// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphParams = { 
/**
 * generations of advisors to include (0–6, default 2)
 */
up?: number, 
/**
 * generations of students to include (0–6, default 2)
 */
down?: number, };
