// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNode = { 
/**
 * generations from the focus: negative for advisors, positive for students
 */
depth: number, id: number, name: string, year: number | null, school: string | null, country: string | null, 
/**
 * students recorded in the database, which may be fewer than the site lists
 */
student_count: number, };
