// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphLink } from "./GraphLink";
import type { GraphNode } from "./GraphNode";

export type Graph = { focus: number, nodes: Array<GraphNode>, links: Array<GraphLink>, 
/**
 * true when the neighbourhood had more than `MAX_GRAPH_NODES` people and the farthest were dropped
 */
truncated: boolean, };
