// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export type PersonDetail = { dissertation: string | null, advisors: Array<Person>, students: Array<Person>, 
/**
 * all descendants reachable in the database, counted once each
 */
descendant_count: number, id: number, name: string, year: number | null, school: string | null, country: string | null, 
/**
 * students recorded in the database, which may be fewer than the site lists
 */
student_count: number, };
