// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mathematician as it appears in lists, search results and graphs.
 */
export type Person = { id: number, name: string, year: number | null, school: string | null, country: string | null, 
/**
 * students recorded in the database, which may be fewer than the site lists
 */
student_count: number, };
