// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stats = { mathematicians: number, relations: number, countries: number, first_year: number | null, last_year: number | null, 
/**
 * RFC 3339 time of the most recent successful page scrape
 */
last_scraped: string | null, };
