// Mathematicians the home page picks from at random: classics an undergraduate meets in their
// courses, and modern names a researcher would know. IDs are MGP's, each checked against its search.

export type Famous = { id: number; name: string; known: string };

export const CLASSICS: Famous[] = [
  { id: 38586, name: "Leonhard Euler", known: "Euler's formula, graph theory" },
  { id: 18231, name: "Carl Friedrich Gauss", known: "Number theory, least squares" },
  { id: 18232, name: "Bernhard Riemann", known: "The Riemann hypothesis, Riemann surfaces" },
  { id: 7298, name: "David Hilbert", known: "Hilbert spaces, Hilbert's problems" },
  { id: 6967, name: "Emmy Noether", known: "Noether's theorem, abstract algebra" },
  { id: 34227, name: "Henri Poincaré", known: "The Poincaré conjecture, topology" },
  { id: 55177, name: "Augustin-Louis Cauchy", known: "Rigorous analysis, Cauchy sequences" },
  { id: 17864, name: "Joseph-Louis Lagrange", known: "Lagrangian mechanics" },
  { id: 108295, name: "Pierre-Simon Laplace", known: "The Laplace transform, probability" },
  { id: 17981, name: "Joseph Fourier", known: "Fourier series" },
  { id: 17946, name: "Peter Gustav Lejeune Dirichlet", known: "Dirichlet's theorem on primes" },
  { id: 7486, name: "Karl Weierstrass", known: "ε–δ analysis" },
  { id: 29561, name: "Georg Cantor", known: "Set theory, sizes of infinity" },
  { id: 7401, name: "Felix Klein", known: "The Erlangen program, the Klein bottle" },
  { id: 15635, name: "Carl Gustav Jacob Jacobi", known: "Elliptic functions, the Jacobian" },
  { id: 18235, name: "Sophus Lie", known: "Lie groups" },
  { id: 29675, name: "Hermann Minkowski", known: "Minkowski spacetime" },
  { id: 60985, name: "Gottfried Wilhelm Leibniz", known: "Calculus, binary numbers" },
  { id: 74313, name: "Isaac Newton", known: "Calculus, laws of motion" },
  { id: 18233, name: "Richard Dedekind", known: "Dedekind cuts, ideals" },
  { id: 86693, name: "Henri Lebesgue", known: "Lebesgue integration" },
  { id: 53213, name: "John von Neumann", known: "Game theory, the stored-program computer" },
  { id: 19539, name: "Kurt Gödel", known: "The incompleteness theorems" },
  { id: 8014, name: "Alan Turing", known: "Turing machines, computability" },
  { id: 10480, name: "Andrey Kolmogorov", known: "The axioms of probability" },
  { id: 7373, name: "Hermann Weyl", known: "Representation theory, gauge theory" },
  { id: 17806, name: "G. H. Hardy", known: "Analytic number theory" },
  { id: 54440, name: "Jacob Bernoulli", known: "The law of large numbers" },
];

export const MODERN: Famous[] = [
  { id: 43967, name: "Terence Tao", known: "Harmonic analysis, the Green–Tao theorem" },
  { id: 9696, name: "Andrew Wiles", known: "Fermat's Last Theorem" },
  { id: 84354, name: "Grigori Perelman", known: "The Poincaré conjecture" },
  { id: 31245, name: "Alexander Grothendieck", known: "Schemes, modern algebraic geometry" },
  { id: 34222, name: "Jean-Pierre Serre", known: "Algebraic topology, number theory" },
  { id: 30949, name: "Michael Atiyah", known: "The Atiyah–Singer index theorem" },
  { id: 31293, name: "Edward Witten", known: "String theory, topological field theory" },
  { id: 91093, name: "Maryam Mirzakhani", known: "Moduli spaces of Riemann surfaces" },
  { id: 160930, name: "Peter Scholze", known: "Perfectoid spaces" },
  { id: 19470, name: "Paul Erdős", known: "Combinatorics, the probabilistic method" },
  { id: 18590, name: "John Nash", known: "Nash equilibria, embedding theorems" },
  { id: 15157, name: "John Milnor", known: "Exotic spheres" },
  { id: 11749, name: "William Thurston", known: "Geometrization of 3-manifolds" },
  { id: 18849, name: "John Horton Conway", known: "The Game of Life, surreal numbers" },
  { id: 31056, name: "Robert Langlands", known: "The Langlands program" },
  { id: 61289, name: "Pierre Deligne", known: "The Weil conjectures" },
  { id: 42920, name: "Claude Shannon", known: "Information theory" },
  { id: 4834, name: "Karen Uhlenbeck", known: "Geometric analysis, gauge theory" },
  { id: 63054, name: "Jean Bourgain", known: "Harmonic analysis, Banach spaces" },
  { id: 201884, name: "Maryna Viazovska", known: "Sphere packing in dimension 8" },
  { id: 185855, name: "June Huh", known: "Combinatorial Hodge theory" },
  { id: 69073, name: "Akshay Venkatesh", known: "Analytic number theory, automorphic forms" },
  { id: 18758, name: "Shing-Tung Yau", known: "Calabi–Yau manifolds" },
  { id: 34220, name: "Alain Connes", known: "Noncommutative geometry" },
  { id: 14999, name: "Mikhael Gromov", known: "Geometric group theory" },
  { id: 44561, name: "Ingrid Daubechies", known: "Wavelets" },
  { id: 60791, name: "Benoit Mandelbrot", known: "Fractals" },
  { id: 10416, name: "Donald Knuth", known: "The Art of Computer Programming, TeX" },
];
